In [ ]:
!pip freeze

In [2]:
import numpy as np

# CREAR DATOS ALEATORIOS

In [3]:
arr = np.random.randint(1,10,(3,2))
arr

array([[6, 6],
       [7, 3],
       [2, 4]])

In [4]:
arr.reshape(1,6)

array([[6, 6, 7, 3, 2, 4]])

In [6]:
arr2 = np.random.randint(1,20,10)
matriz = arr2.reshape(2,5)
matriz

array([[ 8,  2,  1, 14, 15],
       [ 7, 16, 14, 18, 18]])

# FUNCIONES ESTADISTICAS

In [7]:
arr.max()

np.int64(7)

In [8]:
arr.min()

np.int64(2)

In [11]:
matriz.max(1)

array([15, 18])

In [12]:
arr.argmax()

np.int64(2)

In [13]:
arr.min()

np.int64(2)

In [14]:
matriz.min(0)

array([ 7,  2,  1, 14, 15])

In [16]:
arr.sort()
arr

array([[6, 6],
       [3, 7],
       [2, 4]])

In [17]:
np.median(arr)

np.float64(5.0)

In [18]:
np.std(arr)

np.float64(1.7950549357115013)

In [19]:
np.sin(arr)

array([[-0.2794155 , -0.2794155 ],
       [ 0.14112001,  0.6569866 ],
       [ 0.90929743, -0.7568025 ]])

# FILTROS EN NUMPY

In [20]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [21]:
condicion =  arr > 5
condicion

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [22]:
arr[condicion]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [24]:
arr[arr < 5]

array([1, 2, 3, 4], dtype=int8)

In [25]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [26]:
arr_copy = arr.copy()
arr_copy[arr_copy > 5] = 99
arr_copy

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)