# GENERACIÓN DE DATOS ALEATORIOS

In [1]:
import numpy as np

# ARANGE

In [2]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# ZEROS

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# ONES

In [4]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# EYE

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# LINSPACE

In [6]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# RANDOM

In [7]:
np.random.rand()

0.8556778085606296

In [8]:
np.random.rand(4)

array([0.52660432, 0.62818331, 0.5131142 , 0.14971079])

In [9]:
np.random.rand(4,4)

array([[0.84218857, 0.15199694, 0.85821679, 0.03755631],
       [0.794385  , 0.51694547, 0.54703563, 0.49140881],
       [0.72502528, 0.99280369, 0.00262881, 0.00272597],
       [0.78042311, 0.59140102, 0.76940845, 0.29191899]])

In [10]:
np.random.randint(1,100,(10,10))

array([[64,  9,  5, 87, 70, 15, 37, 97, 83, 77],
       [54, 74, 79, 15, 54, 41, 81, 98, 71, 56],
       [50, 85, 35, 30, 71, 86, 56, 30, 88, 32],
       [13, 20, 26, 15, 90, 10, 22, 64, 11, 80],
       [89,  4,  4, 85, 99, 95, 35, 87, 61, 93],
       [78, 39, 45, 20, 19, 17, 75, 18, 44,  1],
       [46, 99, 27, 61, 74,  3, 23, 72, 93, 69],
       [71, 81, 60, 70, 58, 57, 38, 31, 65, 33],
       [16, 10, 98, 81, 90, 32, 93, 49, 58,  5],
       [25, 38, 14, 88, 18, 25, 80, 93, 98, 86]])