# IMPORTAR LIBRERIA

In [1]:
import numpy as np

# CONVERTIR LISTAS EN NUMPY ARRAYS

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(lista)

list

In [5]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(arr)

numpy.ndarray

# TIPOS DE DATOS EN NUMPY ARRAY

In [7]:
arr.dtype

dtype('int64')

In [9]:
arr_float = np.array([1,2,3,4],dtype='float64')
print(arr_float.dtype)
arr_float

float64


array([1., 2., 3., 4.])

# CAST DE TIPO DE DATOS

In [12]:
arr = np.array([1,0,3,4])
arr_bool = arr.astype(np.bool_)
arr_bool.dtype

dtype('bool')

In [13]:
arr_bool

array([ True, False,  True,  True])