# FUNCIONES MAS COMUNES EN NUMPY

In [1]:
import numpy as np

# SHAPE Y RESHAPE

In [2]:
arr = np.random.randint(1,10,(3,2))
arr

array([[5, 4],
       [7, 4],
       [3, 4]])

In [3]:
arr.shape

(3, 2)

In [4]:
arr.ndim

2

In [5]:
arr.reshape(1,6)

array([[5, 4, 7, 4, 3, 4]])

In [6]:
arr.ndim

2

# MAX Y ARGMAX

In [7]:
arr = np.random.randint(1,20,10)
arr

array([ 5, 10,  1, 17, 19,  9,  4, 14,  4, 16])

In [13]:
matriz = arr.reshape(2,5)
matriz

array([[ 5, 10,  1, 17, 19],
       [ 9,  4, 14,  4, 16]])

In [9]:
arr.max()

np.int64(19)

In [10]:
matriz.max()

np.int64(19)

In [11]:
arr.argmax()

np.int64(4)

# MIN Y ARGMIN

In [14]:
arr.min()

np.int64(1)

In [16]:
matriz.min(0)

array([ 5,  4,  1,  4, 16])

# SORT

In [17]:
arr

array([ 5, 10,  1, 17, 19,  9,  4, 14,  4, 16])

In [19]:
arr.sort()
arr

array([ 1,  4,  4,  5,  9, 10, 14, 16, 17, 19])