In [2]:
import numpy as np

# Paso 1: Genera un array con 30 valores aleatorios entre 15 y 40 (temperaturas diarias en °C)

In [3]:
temperaturas = np.random.uniform(15,40,30)
temperaturas

array([26.63466248, 19.67068182, 18.60499912, 28.50799702, 25.55909525,
       37.16855009, 30.77987346, 23.80985789, 36.89269088, 27.61261604,
       21.83948824, 28.50699751, 22.35085459, 31.0777172 , 17.89733752,
       39.00695899, 17.53261886, 39.37817463, 36.04254317, 34.47126321,
       15.69456224, 22.9885027 , 15.84728812, 17.70557328, 19.91023602,
       19.15764767, 15.4702742 , 37.00692261, 17.03062895, 22.44067105])

# PASO 2- DIVIDIMOS LA DATA EN UNA MATRIZ DE 5X6 PARA TENER LA TEMPERATURA POR SEMANA

In [5]:
matriz_temp = temperaturas.reshape(5,6)
matriz_temp

array([[26.63466248, 19.67068182, 18.60499912, 28.50799702, 25.55909525,
        37.16855009],
       [30.77987346, 23.80985789, 36.89269088, 27.61261604, 21.83948824,
        28.50699751],
       [22.35085459, 31.0777172 , 17.89733752, 39.00695899, 17.53261886,
        39.37817463],
       [36.04254317, 34.47126321, 15.69456224, 22.9885027 , 15.84728812,
        17.70557328],
       [19.91023602, 19.15764767, 15.4702742 , 37.00692261, 17.03062895,
        22.44067105]])

# Paso 3: Encuentra:
# - La temperatura máxima por semana
# - El día (índice) en que ocurrió la temperatura máxima por semana
# - La semana con mayor temperatura global

La temperatura máxima por semana

In [7]:
max_semana = np.max(matriz_temp,axis=1)
max_semana

array([37.16855009, 36.89269088, 39.37817463, 36.04254317, 37.00692261])

El día (índice) en que ocurrió la temperatura máxima por semana

In [9]:
indice_max_semana = np.argmax(matriz_temp,axis=1)
indice_max_semana

array([5, 2, 5, 0, 3])

La semana con mayor temperatura global

In [10]:
semana_max_global = np.argmax(max_semana)
semana_max_global

np.int64(2)

In [11]:
# Paso 1: Genera una matriz de 10 alumnos x 3 exámenes (notas aleatorias entre 0 y 20)
notas = np.random.randint(0, 21, size=(10, 3))
notas

array([[12,  4,  7],
       [ 6, 18,  3],
       [ 7, 12, 16],
       [ 4,  3,  0],
       [18,  4, 18],
       [10, 11, 19],
       [ 1,  9, 17],
       [13, 15, 13],
       [ 5, 12,  8],
       [ 0, 19, 16]])

# Encuentra:


*  El alumno con el mejor promedio
*  El examen donde el promedio general fue más bajo
* Ordena a los alumnos según su nota en el primer examen (índice 0)
